version: '3'
services:
  app:
    build: .
    image: sdride-api:version-0.0.1
    ports:
      - 8000:3000
    volumes:
      - type: bind
        source: ./app
        target: /app
    env_file:
      - app/.env
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27027
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - type: volume
        source: sdride-mongodb-volume
        target: /data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
      - mongodb
    depends_on:
      - mongodb
volumes:
  sdride-mongodb-volume:
    external: true